### ISSUE TITLE
Throws exception on restart

### ISSUE THREAD

**Issue by chicagoandy** [Fiercefish1/Zigbee-Lock-Manager#3]
Getting the following exception at startup:

2024-11-26 09:48:58.737 WARNING (MainThread) [custom_components.zigbee_lock_manager.zha_manager] automation.reload service not available at this time
2024-11-26 09:48:59.738 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Zigbee Lock Manager - front_door_lock for zigbee_lock_manager
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zigbee_lock_manager/__init__.py", line 23, in async_setup_entry
    await hass.services.async_call("automation", "reload")
  File "/usr/src/homeassistant/homeassistant/core.py", line 2735, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Action automation.reload not found

**Comment by Fiercefish1** [comment]
What version of HA are your running? 
Is this preventing the integration from starting?  What if you try reloading from the integration page after restart? (Curious if that works)
On my test HA instance (Core 2024.12.0), I get a warning that automation.reload isn't availably during startup, but this doesn't impact HA ability to start and the integration doesn't need it during startup so it can be ignored.

**Comment by kevinwestby** [comment]
Getting something similar......when hub is rebooted. It consistently does not start.  Doing a quick manual reload fixes it.....but not ideal.  All my other integrations start up as expected.  

Running the following HA versions

Core
2025.3.4
Supervisor
2025.03.4
Operating System
15.1
Frontend
20250306.0

Logger: homeassistant.config_entries
Source: config_entries.py:753
First occurred: 1:29:08 PM (2 occurrences)
Last logged: 1:29:09 PM

Error setting up entry Zigbee Lock Manager - lock_butler_pantry for zigbee_lock_manager
Error setting up entry Zigbee Lock Manager - lock_boiler_room for zigbee_lock_manager
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 753, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zigbee_lock_manager/__init__.py", line 23, in async_setup_entry
    await hass.services.async_call("automation", "reload")
  File "/usr/src/homeassistant/homeassistant/core.py", line 2727, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Action automation.reload not found

**Comment by stcbus** [comment]
Confirm this is still an issue for me as well. Have to manually reload integration after every HA reboot.

**Comment by chicagoandy** [comment]
Confirming that there is no practical impact of this bug, but it sure is annoying to have a broken integration on every startup.

It sure does send the message that we shouldn't be using this integration.

Core : 2025.5.1
Supervisor : 2025.05.1
Operating System : 15.2
Frontend : 20250509.0

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 8:04:00 AM (1 occurrence)
Last logged: 8:04:00 AM

Error setting up entry Zigbee Lock Manager - front_door_lock for zigbee_lock_manager
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zigbee_lock_manager/__init__.py", line 23, in async_setup_entry
    await hass.services.async_call("automation", "reload")
  File "/usr/src/homeassistant/homeassistant/core.py", line 2735, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Action automation.reload not found
"

![Image](https://github.com/user-attachments/assets/67a88a1e-c92e-4bc9-9f69-a99b09dd00dc)

![Image](https://github.com/user-attachments/assets/2defe1a3-9eb4-4878-b0ec-04d5830800eb)
